# Google Login related
GOOGLE_CLIENT_ID: "796679159105-6335p2q2ub5pr15lnf3g2cqkhnucmvkl.apps.googleusercontent.com"

#Upload Related
UPLOAD_DIR: "./upload"

# Submission related
DAILY_SUBMIT_LIMIT: 1000
WEEKLY_SUBMIT_LIMIT: 1000
HIDDEN_DAILY_SUBMIT_LIMIT: 1000
HIDDEN_WEEKLY_SUBMIT_LIMIT: 2

# Metrics related
UNZIP_TIMEOUT: "30s"
GROUND_TRUTH_ROOT: "./inference/truth/"

# Public
## Individual submission info
INDIVIDUAL_SUBMISSION_INFO:
    FILE:
        - aoeTimeUpload
        - task
        - showOnLeaderboard
        - submitName
        - modelURL
        - modelDesc
        - stride
        - inputFormat
        - corpus
        - paramDesc
        - paramShared
        - fineTunedParam
        - taskSpecParam
        - state
        - stateInfo
        - submitUUID
    SCORE:
        - PR_per_public
        - KS_acc_public
        - IC_acc_public
        - SID_acc_public
        - ER_acc_public
        - ERfold1_acc_public
        - ERfold2_acc_public
        - ERfold3_acc_public
        - ERfold4_acc_public
        - ERfold5_acc_public
        - ASR_wer_public
        - ASR_LM_wer_public
        - QbE_mtwv_public
        - SF_f1_public
        - SF_cer_public
        - SV_eer_public
        - SD_der_public

## Leaderboard shown data
LEADERBOARD_INFO:
    FILE:
        - aoeTimeUpload
        - task
        - submitName
        - modelURL
        - modelDesc
        - stride
        - inputFormat
        - corpus
        - paramDesc
        - paramShared
        - fineTunedParam
        - taskSpecParam
    SCORE:
        - PR_per_public
        - KS_acc_public
        - IC_acc_public
        - SID_acc_public
        - ER_acc_public
        - ERfold1_acc_public
        - ERfold2_acc_public
        - ERfold3_acc_public
        - ERfold4_acc_public
        - ERfold5_acc_public
        - ASR_wer_public
        - ASR_LM_wer_public
        - QbE_mtwv_public
        - SF_f1_public
        - SF_cer_public
        - SV_eer_public
        - SD_der_public


# Hidden
INDIVIDUAL_HIDDEN_SUBMISSION_INFO:
    FILE:
        - aoeTimeUpload
        - task
        - showOnLeaderboard
        - submitName
        - huggingfaceOrganizationName
        - huggingfaceRepoName
        - huggingfaceCommonHash
        - paramShared
        - state
        - stateInfo
        - submitUUID
    SCORE:
        - PR_per_hidden_dev
        - SID_acc_hidden_dev
        - ER_acc_hidden_dev
        - ASR_wer_hidden_dev
        - SV_eer_hidden_dev
        - SD_der_hidden_dev
        - QbE_map_hidden_dev
        - QbE_eer_hidden_dev
        - ST_bleu_hidden_dev
        - SS_sisdri_hidden_dev
        - SE_pesq_hidden_dev
        - SE_stoi_hidden_dev
        - PR_per_hidden_test
        - SID_acc_hidden_test
        - ER_acc_hidden_test
        - ASR_wer_hidden_test
        - SV_eer_hidden_test
        - SD_der_hidden_test
        - QbE_map_hidden_test
        - QbE_eer_hidden_test
        - ST_bleu_hidden_test
        - SS_sisdri_hidden_test
        - SE_pesq_hidden_test
        - SE_stoi_hidden_test

LEADERBOARD_HIDDEN_INFO:
    FILE:
        - aoeTimeUpload
        - task
        - submitName
        - huggingfaceOrganizationName
        - huggingfaceRepoName
        - huggingfaceCommonHash
        - paramShared
    SCORE:
        - PR_per_hidden_dev
        - SID_acc_hidden_dev
        - ER_acc_hidden_dev
        - ASR_wer_hidden_dev
        - SV_eer_hidden_dev
        - SD_der_hidden_dev
        - QbE_map_hidden_dev
        - QbE_eer_hidden_dev
        - ST_bleu_hidden_dev
        - SS_sisdri_hidden_dev
        - SE_pesq_hidden_dev
        - SE_stoi_hidden_dev
        - PR_per_hidden_test
        - SID_acc_hidden_test
        - ER_acc_hidden_test
        - ASR_wer_hidden_test
        - SV_eer_hidden_test
        - SD_der_hidden_test
        - QbE_map_hidden_test
        - QbE_eer_hidden_test
        - ST_bleu_hidden_test
        - SS_sisdri_hidden_test
        - SE_pesq_hidden_test
        - SE_stoi_hidden_test
